# Config Version 1.1 // Requires MAIN 1.6

# How long until the bot begins spamming. Default = 7
WaitTime: 5

# For social medias which have a message cool down, mainly for Discord. Default = 'false'
ChillZone: 'true'

# How many seconds between each message. Default = 0
MessageDelay: 0

# Should the script be looped? False/True
script_loop: True

# Stop Button // NOTE: If using with loops, the script must have done at least 1 (one) loop! (working on a fix)
stop_key: 'q'
